### ISSUE TITLE
Problem when generating docker container

### ISSUE THREAD

**Issue by Mambix** [Mambix/yobit#2]
```
Collecting YoBit==0.0.1.1 (from -r requirements.txt (line 20))
  Downloading https://files.pythonhosted.org/packages/97/84/4ae53f246d394203cba164dd7930c6c07c90771836af3a84631eae0057fd/YoBit-0.0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-WabWW7/YoBit/setup.py", line 15, in <module>
        exec(f.read(), about)
      File "<string>", line 1, in <module>
      File "YoBit/__init__.py", line 15, in <module>
        import requests
    ImportError: No module named requests
```

**Comment by axeoman** [comment]
https://github.com/Mambix/yobit/pull/3

**Comment by Wegazz** [comment]
Is this project not developing anymore?

**Comment by axeoman** [comment]
I believe it's not
